project:
  type: book

book:
  title: "Filosofia para o Enem"
  author: "Heitor Cova Gama"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    lang: pt-BR
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    lang: pt-BR



